### ISSUE TITLE
apresentação encontro rede AESTS para 25/09

### ISSUE THREAD

**Issue by Andrelamor** [o-futuro-ja-comecou/novas-ideias#27]
@gabrielbdornas listei os tópicos aqui, por enquanto: https://github.com/Andrelamor/aests-seplag/blob/main/topicos.md
- pensei em abordar com muito mais contexto a trajetória geral nossa na diretoria, para justificar como conseguimos o que conseguimos, sendo os principais exemplos de governo aberto:
    - o PdA lançado, de fato, com 30 conjuntos, sendo metade num ETL com ferramentas open, mais um punhado com ferramentas automatizadas (new-dataset-template);
    - o projeto gestão à vista Stefanini;
    - manuais e guias em sites estáticos
    - entendo que estes produtos/entregas só foram possíveis depois da criação de uma cultura de aprendizagem em equipe, com o emprego e uso constante de ferramentas de gestão do trabalho e do conhecimento (mais abrangente que gestão de tickets e controle de versão)
- a formatação não ficou boa, pq tentei marcar os slides/páginas e fazer os subtítulos ao mesmo tempo
- acho que a enquete fecha 11/09, então tem tempo útil de 2 semanas antes da apresentação - se ela for eleita na enquete!

**Comment by gabrielbdornas** [comment]
@Andrelamor, entendi que a apresentação não irá mais acontecer para o evento do dia 25/09:

> Bom dia! Tudo bem? ☀️
Estou passando para agradecer enormemente sua participação em nossa enquete do 5º Encontro da Rede Estratégia 👍 Desta vez, a Troca de Experiências mais votada foi a opção "SEDESE: Escritório de Dados"; já o Curso com Certificação mais votado foi "SEINFRA: Inteligência Artificial para Serviços Públicos". Foram 71 votos computados e o evento será no dia 25/09. Obrigado!

Mesmo assim, acredito que podemos continuar esta construção. Quem sabe para o próximo mês. Faz sentido?
Criei também um Issue para configurarmos o [reveal.js](#4) nesta organização. Assim podemos aproveitar este estilo de apresentação.
